services:
#    urbik_user.example:
#        class: Urbik\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  urbik_user.email.application_mailer:
    class: Urbik\UserBundle\Email\RegistrationMail
    arguments: ["@mailer", "@doctrine"]

  urbik_user.email.registration_listener:
    class: Urbik\UserBundle\Email\RegistrationListener
    arguments:
      - "@urbik_user.email.application_mailer"
    tags:
      - { name: doctrine.event_listener, event: postPersist }

  urbik_user.twig.country_extension:
    class: Urbik\UserBundle\Twig\CountryExtension
    tags:
      - { name: twig.extension }