<?php

namespace Urbik\UserBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    // function which returns an array of users sorted by country
    public function sortedUsers()
    {
        return $this
        ->createQueryBuilder('a')
        ->orderBy('a.country')
        ->getQuery()
        ->getResult()
        ;
    }

    // Returns an array of all registered users'countries
      
    public function onlyCountries()
    {
        $query = $this->_em->createQuery('SELECT DISTINCT a.country FROM UrbikUserBundle:User a ORDER BY a.country');
        $result = $query->getResult();

        return $result;
    }
}
