<?php

namespace Urbik\UserBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function sortedUsers()
    {
        return $this
        ->createQueryBuilder('a')
        ->orderBy('a.country')
        ->getQuery()
        ->getResult()
        ;
    }
}
